abbreviations = {
    "kaba</i>": "Kaba",
    "ekon.</i>": "Ekon.",
    "tkz.</i>": "Kaba/Argo",
    "alay</i>": "Alay",
    "tar.</i>":"Tarih",
    "tek.</i>": "Teknoloji",
    "mat.</i>": "Matematik",
    "tiy.</i>": "Tiyatro",
    "den.</i>": "Denizcilik",
    "ask.</i>": "Askeri",
    "esk.</i>": "Eski Türkçe",
    "kim.</i>": "Kimya",
    "hlk.</i>": "Halk Dili",
    "tıp</i>": "Tıp",
    "tic.</i>": "Ticaret",
    "mec.</i>": "Mecaz",
    "hkr.</i>": "Hakaret",
    "huk.</i>": "Hukuk",
    "sp.</i>": "Spor",
    "şaka</i>": "Şaka",
    "argo</i>": "Kaba/Argo",
}
